#!/usr/bin/env python3
"""Generates lib/ppg/ppg_coefs.h: the Butterworth filters of the PPG pipeline.

The firmware runs the same filters as tools/procesamiento.py (scipy.signal.butter):
a band-pass for the AC component and a low-pass for the DC component, plus a wider
band-pass used only to draw the pulse on the screen. The device does not design them:
this script does, with scipy, and writes the second-order sections as constants. The
design parameters are read from include/config.h (SENSOR_FS_HZ, FILTER_ORDER,
BAND_LOW_HZ, BAND_HIGH_HZ, DC_CUTOFF_HZ, VIEW_FILTER_ORDER, VIEW_BAND_LOW_HZ,
VIEW_BAND_HIGH_HZ), so there is a single place to change them. Run it again after any
change there.

Requirements (the rest of the firmware does not need them):
    pip install scipy

Usage, from firmware/pulsox:
    python tools/gen_ppg_coefs.py [--config PATH] [--out PATH]
"""

import argparse
import re
from pathlib import Path

from scipy.signal import butter

ROOT = Path(__file__).resolve().parent.parent
NAMES = ("SENSOR_FS_HZ", "FILTER_ORDER", "BAND_LOW_HZ", "BAND_HIGH_HZ", "DC_CUTOFF_HZ",
         "VIEW_FILTER_ORDER", "VIEW_BAND_LOW_HZ", "VIEW_BAND_HIGH_HZ")


def read_config(path: Path) -> dict[str, float]:
    """Pulls the numeric `#define NAME value` lines the filters depend on."""
    text = path.read_text(encoding="utf-8")
    values = {}
    for name in NAMES:
        m = re.search(rf"^#define\s+{name}\s+([0-9.]+)f?\b", text, re.MULTILINE)
        if not m:
            raise SystemExit(f"{path}: no encuentro '#define {name} <numero>'")
        values[name] = float(m.group(1))
    return values


def sections(sos) -> str:
    rows = []
    for b0, b1, b2, a0, a1, a2 in sos:
        assert abs(a0 - 1.0) < 1e-12, "scipy normalizes a0 to 1"
        rows.append("  {%s, %s, %s, %s, %s}," % tuple(repr(float(v)) for v in (b0, b1, b2, a1, a2)))
    return "\n".join(rows)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--config", type=Path, default=ROOT / "include" / "config.h")
    ap.add_argument("--out", type=Path, default=ROOT / "lib" / "ppg" / "ppg_coefs.h")
    args = ap.parse_args()

    c = read_config(args.config)
    fs, order = c["SENSOR_FS_HZ"], int(c["FILTER_ORDER"])
    low, high, dc = c["BAND_LOW_HZ"], c["BAND_HIGH_HZ"], c["DC_CUTOFF_HZ"]
    if fs != int(fs):
        raise SystemExit("SENSOR_FS_HZ tiene que ser un numero entero de Hz")

    vorder, vlow, vhigh = int(c["VIEW_FILTER_ORDER"]), c["VIEW_BAND_LOW_HZ"], c["VIEW_BAND_HIGH_HZ"]

    bp = butter(order, [low, high], btype="band", fs=fs, output="sos")
    lp = butter(order, dc, btype="low", fs=fs, output="sos")
    view = butter(vorder, [vlow, vhigh], btype="band", fs=fs, output="sos")

    out = f"""\
// Generated by tools/gen_ppg_coefs.py from include/config.h. Do not edit.
//
// Butterworth filters of the PPG pipeline, as second-order sections (a0 = 1),
// sample rate {fs:g} Hz:
//   PPG_BP_SOS    band-pass {low:g}-{high:g} Hz, order {order}   (AC component, for SpO2 and heart rate)
//   PPG_LP_SOS    low-pass  {dc:g} Hz, order {order}         (DC component)
//   PPG_VIEW_SOS  band-pass {vlow:g}-{vhigh:g} Hz, order {vorder}  (only to draw the pulse on the screen)
#pragma once
#include "sos_filter.h"

#define PPG_COEFS_FS_HZ {int(fs)}
#define PPG_BP_SECTIONS {len(bp)}
#define PPG_LP_SECTIONS {len(lp)}
#define PPG_VIEW_SECTIONS {len(view)}

static const SosSection PPG_BP_SOS[PPG_BP_SECTIONS] = {{
{sections(bp)}
}};

static const SosSection PPG_LP_SOS[PPG_LP_SECTIONS] = {{
{sections(lp)}
}};

static const SosSection PPG_VIEW_SOS[PPG_VIEW_SECTIONS] = {{
{sections(view)}
}};
"""
    args.out.write_text(out, encoding="utf-8", newline="\n")
    print(f"Escrito {args.out} ({len(bp)} secciones pasabanda, {len(lp)} pasabajos, {len(view)} de visualizacion)")


if __name__ == "__main__":
    main()
