// Generated by tools/gen_ppg_coefs.py from include/config.h. Do not edit.
//
// Butterworth filters of the PPG pipeline, as second-order sections (a0 = 1),
// sample rate 100 Hz:
//   PPG_BP_SOS    band-pass 0.5-4 Hz, order 4   (AC component, for SpO2 and heart rate)
//   PPG_LP_SOS    low-pass  0.2 Hz, order 4         (DC component)
//   PPG_VIEW_SOS  band-pass 0.5-10 Hz, order 2  (only to draw the pulse on the screen)
#pragma once
#include "sos_filter.h"

#define PPG_COEFS_FS_HZ 100
#define PPG_BP_SECTIONS 4
#define PPG_LP_SECTIONS 2
#define PPG_VIEW_SECTIONS 2

static const SosSection PPG_BP_SOS[PPG_BP_SECTIONS] = {
  {0.00011138107559506853, 0.00022276215119013706, 0.00011138107559506853, -1.6766954582488076, 0.7108019089468294},
  {1.0, 2.0, 1.0, -1.806759060864077, 0.8625897096353131},
  {1.0, -2.0, 1.0, -1.933393151192315, 0.9349063027928723},
  {1.0, -2.0, 1.0, -1.9796314851310104, 0.9806565775245344},
};

static const SosSection PPG_LP_SOS[PPG_LP_SECTIONS] = {
  {1.5332455206019598e-09, 3.0664910412039195e-09, 1.5332455206019598e-09, -1.9768913542871203, 0.977047453642916},
  {1.0, 2.0, 1.0, -1.990271241661728, 0.9904283975206014},
};

static const SosSection PPG_VIEW_SOS[PPG_VIEW_SECTIONS] = {
  {0.06186949746297043, 0.12373899492594086, 0.06186949746297043, -1.1954325155143635, 0.45055523366132333},
  {1.0, -2.0, 1.0, -1.9559289715351784, 0.9569862817098911},
};
